/**
 * Campus Building Data
 * Based on Faculty of Medicine floor plan
 */

const CAMPUS_DATA = {
  // Campus center coordinates (Update with actual coordinates)
  center: [80.5728, 6.1157],
  zoom: 17,

  // All buildings with their details
  buildings: [
    // ADMIN BLOCK (1-8)
    {
      id: 1,
      number: "1",
      name: "Auditorium",
      category: "admin",
      floor: "Ground Floor",
      description: "Main auditorium for ceremonies and large events",
      coordinates: [80.5732, 6.1162],
      icon: "🎭",
      color: "#e74c3c",
    },
    {
      id: 2,
      number: "2",
      name: "Dean Office",
      category: "admin",
      floor: "Ground Floor",
      description: "Faculty of Medicine administrative office",
      coordinates: [80.5733, 6.1163],
      icon: "🏢",
      color: "#e74c3c",
    },
    {
      id: 3,
      number: "3",
      name: "Library",
      category: "admin",
      floor: "1st Floor",
      description: "Medical library and study area",
      coordinates: [80.5734, 6.1164],
      icon: "📚",
      color: "#e74c3c",
    },
    {
      id: 4,
      number: "4",
      name: "CAL Lab",
      category: "admin",
      floor: "2nd Floor",
      description: "Computer Assisted Learning Laboratory",
      coordinates: [80.5735, 6.1165],
      icon: "💻",
      color: "#e74c3c",
    },
    {
      id: 5,
      number: "5",
      name: "Canteen",
      category: "admin",
      floor: "2nd Floor",
      description: "Student and staff cafeteria",
      coordinates: [80.5736, 6.1166],
      icon: "🍽️",
      color: "#e74c3c",
    },
    {
      id: 6,
      number: "6",
      name: "Lecture Theatre A",
      category: "admin",
      floor: "3rd Floor",
      description: "Main lecture hall A",
      coordinates: [80.5737, 6.1167],
      icon: "🎓",
      color: "#e74c3c",
    },
    {
      id: 7,
      number: "7",
      name: "Lecture Theatre B",
      category: "admin",
      floor: "3rd Floor",
      description: "Main lecture hall B",
      coordinates: [80.5738, 6.1168],
      icon: "🎓",
      color: "#e74c3c",
    },
    {
      id: 8,
      number: "8",
      name: "Lecture Theatre C",
      category: "admin",
      floor: "3rd Floor",
      description: "Main lecture hall C",
      coordinates: [80.5739, 6.1169],
      icon: "🎓",
      color: "#e74c3c",
    },

    // DEPARTMENT BLOCK (9-16)
    {
      id: 9,
      number: "9",
      name: "Department of Forensic Medicine",
      category: "department",
      floor: "Ground Floor",
      description: "Forensic medicine department and laboratories",
      coordinates: [80.5729, 6.116],
      icon: "🔬",
      color: "#3498db",
    },
    {
      id: 10,
      number: "10",
      name: "Department of Pathology",
      category: "department",
      floor: "1st Floor",
      description: "Pathology department and diagnostic facilities",
      coordinates: [80.5728, 6.1159],
      icon: "🧬",
      color: "#3498db",
    },
    {
      id: 11,
      number: "11",
      name: "Department of Community Medicine",
      category: "department",
      floor: "2nd Floor",
      description: "Community medicine and public health",
      coordinates: [80.5727, 6.1158],
      icon: "🏥",
      color: "#3498db",
    },
    {
      id: 12,
      number: "12",
      name: "Department of Physiology",
      category: "department",
      floor: "3rd Floor",
      description: "Physiology research and teaching",
      coordinates: [80.5726, 6.1157],
      icon: "❤️",
      color: "#3498db",
    },
    {
      id: 13,
      number: "13",
      name: "Department of Pharmacology",
      category: "department",
      floor: "2nd Floor",
      description: "Pharmacology and drug research",
      coordinates: [80.5725, 6.1156],
      icon: "💊",
      color: "#3498db",
    },
    {
      id: 14,
      number: "14",
      name: "Lecture Theatre D",
      category: "department",
      floor: "3rd Floor",
      description: "Department lecture hall",
      coordinates: [80.5724, 6.1155],
      icon: "🎓",
      color: "#3498db",
    },
    {
      id: 15,
      number: "15",
      name: "Department of Microbiology",
      category: "department",
      floor: "2nd Floor",
      description: "Microbiology labs and research",
      coordinates: [80.5723, 6.1154],
      icon: "🦠",
      color: "#3498db",
    },
    {
      id: 16,
      number: "16",
      name: "Department of Parasitology",
      category: "department",
      floor: "3rd Floor",
      description: "Parasitology research facility",
      coordinates: [80.5722, 6.1153],
      icon: "🔬",
      color: "#3498db",
    },

    // ANATOMY BLOCK (17-19)
    {
      id: 17,
      number: "17",
      name: "Department of Biochemistry",
      category: "anatomy",
      floor: "2nd Floor",
      description: "Biochemistry labs and teaching",
      coordinates: [80.5721, 6.1159],
      icon: "⚗️",
      color: "#2ecc71",
    },
    {
      id: 18,
      number: "18",
      name: "Department of Anatomy",
      category: "anatomy",
      floor: "1st Floor",
      description: "Anatomy dissection halls and museum",
      coordinates: [80.572, 6.1158],
      icon: "🫀",
      color: "#2ecc71",
    },
    {
      id: 19,
      number: "19",
      name: "Lecture Theatre E",
      category: "anatomy",
      floor: "3rd Floor",
      description: "Anatomy lecture theatre",
      coordinates: [80.5719, 6.1157],
      icon: "🎓",
      color: "#2ecc71",
    },

    // CLINICAL BLOCK (20-26)
    {
      id: 20,
      number: "20",
      name: "Department of Anesthesiology",
      category: "clinical",
      floor: "Ground Floor",
      description: "Anesthesiology department",
      coordinates: [80.5723, 6.1151],
      icon: "💉",
      color: "#f39c12",
    },
    {
      id: 21,
      number: "21",
      name: "Department of Paediatrics",
      category: "clinical",
      floor: "1st Floor",
      description: "Paediatrics and child health",
      coordinates: [80.5724, 6.115],
      icon: "👶",
      color: "#f39c12",
    },
    {
      id: 22,
      number: "22",
      name: "Department of Obstetrics & Gynaecology",
      category: "clinical",
      floor: "2nd Floor",
      description: "Obstetrics and gynaecology department",
      coordinates: [80.5725, 6.1149],
      icon: "🤱",
      color: "#f39c12",
    },
    {
      id: 23,
      number: "23",
      name: "Department of Psychiatry",
      category: "clinical",
      floor: "3rd Floor",
      description: "Psychiatry and mental health",
      coordinates: [80.5726, 6.1148],
      icon: "🧠",
      color: "#f39c12",
    },
    {
      id: 24,
      number: "24",
      name: "Department of Medicine",
      category: "clinical",
      floor: "1st Floor",
      description: "General medicine department",
      coordinates: [80.5727, 6.1147],
      icon: "⚕️",
      color: "#f39c12",
    },
    {
      id: 25,
      number: "25",
      name: "Department of Surgery",
      category: "clinical",
      floor: "2nd Floor",
      description: "Surgery department and skills lab",
      coordinates: [80.5728, 6.1146],
      icon: "🔪",
      color: "#f39c12",
    },
    {
      id: 26,
      number: "26",
      name: "Clinical Lecture Theatre",
      category: "clinical",
      floor: "3rd Floor",
      description: "Clinical teaching theatre",
      coordinates: [80.5729, 6.1145],
      icon: "🎓",
      color: "#f39c12",
    },

    // HOSTELS (27-29)
    {
      id: 27,
      number: "27",
      name: "Girls Hostel",
      category: "hostel",
      floor: "Multi-story",
      description: "Female student accommodation",
      coordinates: [80.574, 6.117],
      icon: "🏠",
      color: "#9b59b6",
    },
    {
      id: 28,
      number: "28",
      name: "Boys Hostel",
      category: "hostel",
      floor: "Multi-story",
      description: "Male student accommodation",
      coordinates: [80.5741, 6.1171],
      icon: "🏠",
      color: "#9b59b6",
    },
    {
      id: 29,
      number: "29",
      name: "Boys Hostel",
      category: "hostel",
      floor: "Multi-story",
      description: "Male student accommodation (Block 2)",
      coordinates: [80.5742, 6.1172],
      icon: "🏠",
      color: "#9b59b6",
    },
    {
      id: 30,
      number: "30",
      name: "Girls Hostel",
      category: "hostel",
      floor: "Multi-story",
      description: "Female student accommodation (Block 2)",
      coordinates: [80.5743, 6.1173],
      icon: "🏠",
      color: "#9b59b6",
    },
  ],

  // Additional landmarks
  landmarks: [
    {
      id: "gate-a",
      name: "Main Gate",
      type: "entrance",
      coordinates: [80.572, 6.115],
      icon: "🚪",
      description: "Main entrance to Faculty of Medicine",
    },
    {
      id: "pond",
      name: "Pond",
      type: "landmark",
      coordinates: [80.573, 6.1155],
      icon: "💧",
      description: "Campus pond and recreation area",
    },
    {
      id: "gate-c",
      name: "Second Gate",
      type: "entrance",
      coordinates: [80.5735, 6.1145],
      icon: "🚪",
      description: "Secondary campus entrance",
    },
    {
      id: "water-tank",
      name: "Water Tank",
      type: "facility",
      coordinates: [80.5725, 6.114],
      icon: "💦",
      description: "Campus water supply",
    },
  ],

  // Roads around campus
  roads: [
    {
      name: "From Godakanda",
      type: "main-road",
      description: "Main access road from Godakanda",
    },
    {
      name: "From Galle to Wanduramba Road",
      type: "main-road",
      description: "Southern access road",
    },
  ],
};
